{{- $replicaCount := int .Values.controller.replicaCount }}
{{- if and .Values.kraft.enabled (gt $replicaCount 0) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-controller-headless" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    {{- if or (not .Values.kraft.enabled) (not .Values.controller.controllerOnly) }}
    - name: tcp-interbroker
      port: {{ .Values.service.ports.interbroker }}
      protocol: TCP
      targetPort: interbroker
    - name: tcp-client
      port: {{ .Values.service.ports.client }}
      protocol: TCP
      targetPort: client
    {{- end }}
    {{- if .Values.kraft.enabled }}
    - name: tcp-controller
      protocol: TCP
      port: {{ .Values.service.ports.controller }}
      targetPort: controller
    {{- end }}
  selector:
    app.kubernetes.io/component: controller-eligible
    app.kubernetes.io/part-of: kafka
{{- end }}
