apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.rabbitmq.metadata.namespace }}
  name: {{ include "rabbitmq.fullname" . | kebabcase }}-amqp
  labels:
    {{- include "rabbitmq.labels" . |  nindent 4 }}
spec:
  ports:
    - port: {{ .Values.rabbitmq.service.port }}
      targetPort: {{ .Values.rabbitmq.service.targetPort }}
      protocol: TCP
      name: amqp-tcp
    - port: {{ .Values.rabbitmq.service.tlsPort }}
      targetPort: {{ .Values.rabbitmq.service.tlsTargetPort }}
      protocol: TCP
      name: tls-amqp-tcp
  selector:
    {{-  include "rabbitmq.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.rabbitmq.metadata.namespace }}
  name: {{ include "rabbitmq.fullname" . | kebabcase }}-manager
  labels:
    {{- include "rabbitmq.labels" . |  nindent 4 }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - port: {{ .Values.rabbitmq.service.managerPort }}
      targetPort: {{ .Values.rabbitmq.service.targetManagerPort }}
      protocol: TCP
      name: manager-http
    - port: {{ .Values.rabbitmq.service.tlsManagerPort }}
      targetPort: {{ .Values.rabbitmq.service.tlsManagerTargetPort }}
      protocol: TCP
      name: tls-man-http
  selector:
    {{-  include "rabbitmq.selectorLabels" . | nindent 4 }}
